# app.py - Semantic Search FastAPI Service
# Start with: uvicorn app:app --host 0.0.0.0 --port 8000
#
# This file is auto-generated by the main.ipynb notebook.
# It loads pre-computed artifacts (embeddings, models, ChromaDB)
# and provides a REST API for semantic search with caching.

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import numpy as np
import time
import pickle
import chromadb
from sentence_transformers import SentenceTransformer
from collections import defaultdict
from scipy.stats import entropy as scipy_entropy
from typing import Optional


# ══════════════════════════════════════════════════════════════════
# Semantic Cache — hand-written, no external cache libraries
# ══════════════════════════════════════════════════════════════════

class SemanticCache:
    """
    Cluster-partitioned semantic cache.
    Entries are partitioned by dominant cluster for O(n/k) lookup.
    Boundary queries (high entropy) search multiple partitions.
    """

    def __init__(self, threshold=0.85, n_clusters=None):
        self.threshold = threshold
        self.n_clusters = n_clusters
        self.partitions = defaultdict(list)
        self.hit_count = 0
        self.miss_count = 0
        self.total_lookup_time = 0.0

    def _cosine_similarity(self, a: np.ndarray, b: np.ndarray) -> float:
        """Hand-written cosine similarity using only numpy."""
        norm_a = np.linalg.norm(a)
        norm_b = np.linalg.norm(b)
        if norm_a == 0 or norm_b == 0:
            return 0.0
        return float(np.dot(a, b) / (norm_a * norm_b))

    def _get_search_partitions(self, cluster_probs: np.ndarray,
                                entropy_threshold: float = 1.5) -> list:
        """Search dominant partition for clear queries, multiple for ambiguous."""
        ent = scipy_entropy(cluster_probs)
        if ent > entropy_threshold:
            return [i for i, p in enumerate(cluster_probs) if p > 0.2]
        else:
            return [int(np.argmax(cluster_probs))]

    def lookup(self, query_embedding: np.ndarray,
               cluster_probs: np.ndarray) -> tuple:
        """Search cache for semantically similar prior query."""
        start = time.time()
        dominant_cluster = int(np.argmax(cluster_probs))
        partitions_to_search = self._get_search_partitions(cluster_probs)

        best_score = -1.0
        best_entry = None

        for cluster_id in partitions_to_search:
            for entry in self.partitions[cluster_id]:
                score = self._cosine_similarity(
                    query_embedding, entry["embedding"]
                )
                if score > best_score:
                    best_score = score
                    best_entry = entry

        self.total_lookup_time += time.time() - start

        if best_score >= self.threshold:
            self.hit_count += 1
            return best_entry, best_score, dominant_cluster

        self.miss_count += 1
        return None, best_score, dominant_cluster

    def store(self, query: str, embedding: np.ndarray, result: str,
              cluster_probs: np.ndarray) -> None:
        """Store query-result pair in the dominant cluster partition."""
        dominant_cluster = int(np.argmax(cluster_probs))
        entry = {
            "query": query,
            "embedding": embedding,
            "result": result,
            "dominant_cluster": dominant_cluster,
            "cluster_distribution": cluster_probs.tolist(),
            "timestamp": time.time(),
            "access_count": 0
        }
        self.partitions[dominant_cluster].append(entry)

    def flush(self) -> None:
        """Wipe all cache entries and reset stats."""
        self.partitions = defaultdict(list)
        self.hit_count = 0
        self.miss_count = 0
        self.total_lookup_time = 0.0

    def get_stats(self) -> dict:
        total_queries = self.hit_count + self.miss_count
        total_entries = sum(len(v) for v in self.partitions.values())
        return {
            "total_entries": total_entries,
            "hit_count": self.hit_count,
            "miss_count": self.miss_count,
            "hit_rate": round(self.hit_count / total_queries, 3)
                        if total_queries > 0 else 0.0,
            "avg_lookup_time_ms": round(
                (self.total_lookup_time / total_queries * 1000), 3
            ) if total_queries > 0 else 0.0,
            "partition_sizes": {
                k: len(v) for k, v in self.partitions.items()
            }
        }

    def get_all_entries(self) -> list:
        """Return all cache entries for inspection."""
        all_entries = []
        for cluster_id, entries in self.partitions.items():
            for entry in entries:
                all_entries.append({
                    "query": entry["query"],
                    "dominant_cluster": entry["dominant_cluster"],
                    "cluster_distribution": entry["cluster_distribution"],
                    "timestamp": entry["timestamp"]
                })
        return all_entries


# ══════════════════════════════════════════════════════════════════
# Load pre-computed artifacts
# ══════════════════════════════════════════════════════════════════

print("Loading embedding model...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')

print("Loading GMM model...")
with open('gmm.pkl', 'rb') as f:
    gmm = pickle.load(f)

# NOTE: GMM is fit on raw 384-dim embeddings (not UMAP).
# Query embeddings go directly to gmm.predict_proba() — no UMAP step needed.

print("Connecting to ChromaDB...")
chroma_client = chromadb.PersistentClient(path="./chroma_db")
collection = chroma_client.get_collection("newsgroups_collection")
print(f"ChromaDB collection loaded: {collection.count()} documents")

# Initialize semantic cache
cache = SemanticCache(threshold=0.85)

# ══════════════════════════════════════════════════════════════════
# FastAPI Application
# ══════════════════════════════════════════════════════════════════

app = FastAPI(
    title="Semantic Search API",
    description="20 Newsgroups semantic search with fuzzy clustering cache",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Timing Middleware ────────────────────────────────────────────
@app.middleware("http")
async def add_timing_header(request, call_next):
    """Add X-Response-Time-Ms header to every response."""
    start = time.time()
    response = await call_next(request)
    elapsed_ms = round((time.time() - start) * 1000, 2)
    response.headers["X-Response-Time-Ms"] = str(elapsed_ms)
    return response


# ── Request/Response Models ──────────────────────────────────────
class QueryRequest(BaseModel):
    query: str


class QueryResponse(BaseModel):
    query: str
    cache_hit: bool
    matched_query: Optional[str]
    similarity_score: float
    result: str
    dominant_cluster: int


# ── Helper: compute result on cache miss ─────────────────────────
def compute_result(query_embedding, n_results=5):
    """
    On cache miss, query ChromaDB for top-5 most similar documents.
    Returns a formatted string result.
    """
    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=n_results,
        include=["documents", "metadatas", "distances"]
    )
    docs = results["documents"][0]
    metas = results["metadatas"][0]
    formatted = []
    for i, (doc, meta) in enumerate(zip(docs, metas)):
        formatted.append(
            f"[Result {i+1}] Category: {meta.get('category', 'unknown')}\n"
            f"{doc[:300]}..."
        )
    return "\n\n".join(formatted)


# ── Endpoint 1: POST /query ──────────────────────────────────────
@app.post("/query", response_model=QueryResponse)
async def query_endpoint(body: QueryRequest,
                          background_tasks: BackgroundTasks):
    """Semantic search with cache. Returns top-5 similar documents."""
    query_text = body.query.strip()
    if not query_text:
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    # Embed the query using the same model as document embeddings
    query_embedding = embedder.encode(query_text, normalize_embeddings=True)

    # Get cluster membership directly from raw embedding (no UMAP needed)
    cluster_probs = gmm.predict_proba([query_embedding])[0]
    dominant_cluster = int(np.argmax(cluster_probs))

    # Check semantic cache first
    cached_entry, similarity_score, _ = cache.lookup(
        query_embedding, cluster_probs
    )

    if cached_entry is not None:
        return QueryResponse(
            query=query_text,
            cache_hit=True,
            matched_query=cached_entry["query"],
            similarity_score=round(similarity_score, 4),
            result=cached_entry["result"],
            dominant_cluster=dominant_cluster
        )

    # Cache miss — compute result from ChromaDB
    result = compute_result(query_embedding)

    # Store in cache via background task (non-blocking)
    background_tasks.add_task(
        cache.store, query_text, query_embedding, result, cluster_probs
    )

    return QueryResponse(
        query=query_text,
        cache_hit=False,
        matched_query=None,
        similarity_score=round(similarity_score, 4),
        result=result,
        dominant_cluster=dominant_cluster
    )


# ── Endpoint 2: GET /cache/stats ─────────────────────────────────
@app.get("/cache/stats")
async def cache_stats():
    """Return cache performance metrics."""
    return cache.get_stats()


# ── Endpoint 3: DELETE /cache ────────────────────────────────────
@app.delete("/cache")
async def flush_cache():
    """Flush all cache entries and reset stats."""
    cache.flush()
    return {"message": "Cache flushed successfully", "status": "ok"}


# ── Endpoint 4: GET /cache/inspect ───────────────────────────────
@app.get("/cache/inspect")
async def inspect_cache():
    """Debug endpoint: view full cache contents and partition sizes."""
    return {
        "entries": cache.get_all_entries(),
        "partition_sizes": {
            k: len(v) for k, v in cache.partitions.items()
        }
    }


# ── Health Check ─────────────────────────────────────────────────
@app.get("/health")
async def health():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "cache_entries": sum(len(v) for v in cache.partitions.values()),
        "chromadb_docs": collection.count()
    }
